### ISSUE TITLE
msprime.simulate() doesn't support `discrete_genome` param.

### ISSUE THREAD

**Issue by grahamgower** [tskit-dev/pyslim#132]
Recently removed: https://github.com/tskit-dev/msprime/issues/1297
I guess pyslim needs to use the new msprime-1.0 API. E.g. error message from stdpopsim w/ msprime 1.0.0a3 (plus unrelated patches):
```
$ nosetests -x tests/
......................................................................................................................................................................................................E
======================================================================
ERROR: test_simulate_with_mask (tests.test_masking.TestSimulate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/grg/src/stdpopsim/tests/test_masking.py", line 135, in test_simulate_with_mask
    ts = engine.simulate(
  File "/home/grg/src/stdpopsim/stdpopsim/slim_engine.py", line 1124, in simulate
    ts = self._recap_and_rescale(
  File "/home/grg/src/stdpopsim/stdpopsim/slim_engine.py", line 1226, in _recap_and_rescale
    ts = ts.recapitate(
  File "/home/grg/.local/lib/python3.9/site-packages/pyslim/slim_tree_sequence.py", line 473, in recapitate
    recap = msprime.simulate(
TypeError: simulate() got an unexpected keyword argument 'discrete_genome'
```

**Comment by jeromekelleher** [comment]
Unfortunately, yes. pyslim must have been depending on a pre-release already, though, since this was never released.

**Comment by grahamgower** [comment]
Oh, sorry, this is a duplicate of #106.

**Comment by petrelharp** [comment]
Apologies! This is on a code path that no-one got to without using development msprime, btw.
