### ISSUE TITLE
mutation time error when recapitating

### ISSUE THREAD

**Issue by ShyamieG** [tskit-dev/pyslim#350]
Hi all,

I'm running into a "TSK_ERR_MUTATION_TIME_OLDER_THAN_PARENT_NODE" error when trying to recapitate a truncated tree sequence. I've attached [some code and a tree sequence](https://github.com/user-attachments/files/16788184/Archive.zip) to walk through the issue.

The original tree sequence can be recapitated without a problem, but I run into the error when I try to truncate my tree sequence first using the 'delete_older' method:

```
# truncate, then recapitate
max_age = 20000
ts_tables = tree_seq.dump_tables()
ts_tables.delete_older(max_age)
trunc_ts = ts_tables.tree_sequence()

msprime.sim_ancestry(initial_state=trunc_ts, recombination_rate = 1e-9, demography = demography, random_seed = 1234)
```

the above code gave me the following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shyamag/miniconda3/envs/slim-env/lib/python3.9/site-packages/msprime/ancestry.py", line 1226, in sim_ancestry
    return _wrap_replicates(
  File "/Users/shyamag/miniconda3/envs/slim-env/lib/python3.9/site-packages/msprime/ancestry.py", line 660, in _wrap_replicates
    deque = collections.deque(iterator, maxlen=1)
  File "/Users/shyamag/miniconda3/envs/slim-env/lib/python3.9/site-packages/msprime/ancestry.py", line 1518, in run_replicates
    ts = tables.tree_sequence()
  File "/Users/shyamag/miniconda3/envs/slim-env/lib/python3.9/site-packages/tskit/tables.py", line 3341, in tree_sequence
    return tskit.TreeSequence.load_tables(self)
  File "/Users/shyamag/miniconda3/envs/slim-env/lib/python3.9/site-packages/tskit/trees.py", line 4110, in load_tables
    ts.load_tables(tables._ll_tables, build_indexes=build_indexes)
_tskit.LibraryError: A mutation's time must be < the parent node of the edge on which it occurs, or be marked as 'unknown'. (TSK_ERR_MUTATION_TIME_OLDER_THAN_PARENT_NODE)

I found this strange because I'm not simulating any new mutations during recapitation. I also checked for cases where a mutation has an older time than the parent node of its associated edge and found none:

```
# check for bad mutations
for mutation in trunc_ts.mutations():
	mut_time = mutation.time
	parent_node_time = trunc_ts.node(trunc_ts.edge(mutation.edge).parent).time
	if mut_time >= parent_node_time:
		print(mutation)
```

I went ahead and marked all my mutation times as unknown, as suggested by the error message. I don't really need mutation times for my application, so that is a viable workaround for me. However, I feel like this should not be happening and might indicate a bug. Any ideas what might be going on?

Thanks!

**Comment by ShyamieG** [comment]
Sorry, I just realized that there are in fact two mutations that violate the rule. It seems they ended up on edges that no longer exist after I truncate my tree. I can simply remove them and it works.

**Comment by petrelharp** [comment]
Gee, thanks, @ShyamieG - this is an issue. I think that either
1. this is an issue with `msprime.sim_ancestry(initial_state=...)`, in that it needs to check for mutations above the roots and either deal with them properly (either put them on the right branches or error?), or
2. we should decide that this is a User Beware situation and maybe add documentation.

My inclination is (1), and in fact it'd be a pretty easy thing to fix up (ie to put the mutations where they should go?) but I haven't thought about it hard. I'm going to transfer this to msprime.
