### ISSUE TITLE
_msprime LibraryError: Bad population id provided

### ISSUE THREAD

**Issue by ashander** [tskit-dev/pyslim#5]
This is with a version of `simple.trees` that I produced so that could contribute but getting the error below with a `conda install msprime` version 0.6.0:

```sh
 $ python test_reading.py                            
Traceback (most recent call last):                   
  File "test_reading.py", line 4, in <module>        
    ts = pyslim.load("simple.trees", slim_format=True)                                                    
  File "/home/jaime/lib/pyslim/pyslim/slim_tree_sequence.py", line 29, in load                            
    ts = SlimTreeSequence.load(path)                 
  File "/home/jaime/lib/pyslim/pyslim/slim_tree_sequence.py", line 129, in load                           
    ts = msprime.load(path)                          
  File "/home/jaime/miniconda3/envs/pyslim/lib/python3.6/site-packages/msprime/trees.py", line 1161, in load                                                                                                        
    return TreeSequence.load(path)                   
  File "/home/jaime/miniconda3/envs/pyslim/lib/python3.6/site-packages/msprime/trees.py", line 1588, in load                                                                                                        
    ts.load(path)                                    
_msprime.LibraryError: Bad population id provided.   
(pyslim) jaime@shuksan:~/lib/pyslim/tests$ (master)  
 $ which python                                      
/home/jaime/miniconda3/envs/pyslim/bin/python        
(pyslim) jaime@shuksan:~/lib/pyslim/tests$ (master)  
 $ conda list | grep msprime
msprime                   0.6.0            py36hcb787e7_0    conda-forge

```

**Comment by ashander** [comment]
Oops looks like my `simple.trees` was from an out of date SLIM
