### ISSUE TITLE
pyslim.load can't load file with tskit 0.3.0

### ISSUE THREAD

**Issue by grahamgower** [tskit-dev/pyslim#92]
```
$ stdpopsim -e slim --slim-scaling-factor 10 HomSap 10 -l 0.01 -o /tmp/foo.trees
Simulation information:
    Engine: slim (3.4)
    Model id: PiecewiseConstant
    Model desciption: Piecewise constant size population model over multiple epochs.
    Population: number_samples (sampling_time_generations):
        pop0: 10 (0)
Contig Description:
    Contig length: 2492506.21
    Mean recombination rate: 1.1485597641285933e-08
    Mean mutation rate: 1.29e-08
    Genetic map: None

WARNING: You're using a scaling factor (10.0). This should give similar results for many situations, but is not equivalent, especially in the presence of selection. When using rescaling, you should be careful---do checks and compare results across different values of the scaling factor.
Traceback (most recent call last):
  File "/home/grg/.local/bin/stdpopsim", line 8, in <module>
    sys.exit(stdpopsim_main())
  File "/home/grg/.local/lib/python3.8/site-packages/stdpopsim/cli.py", line 651, in stdpopsim_main
    run(args)
  File "/home/grg/.local/lib/python3.8/site-packages/stdpopsim/cli.py", line 642, in run
    args.runner(args)
  File "/home/grg/.local/lib/python3.8/site-packages/stdpopsim/cli.py", line 457, in run_simulation
    ts = engine.simulate(**kwargs)
  File "/home/grg/.local/lib/python3.8/site-packages/stdpopsim/slim_engine.py", line 723, in simulate
    ts = pyslim.load(ts_file.name)
  File "/home/grg/.local/lib/python3.8/site-packages/pyslim/slim_tree_sequence.py", line 29, in load
    ts = SlimTreeSequence.load(path)
  File "/home/grg/.local/lib/python3.8/site-packages/pyslim/slim_tree_sequence.py", line 179, in load
    return cls(ts, reference_sequence)
  File "/home/grg/.local/lib/python3.8/site-packages/pyslim/slim_tree_sequence.py", line 150, in __init__
    npops = [len(set(self.node(n).population for n in ind.nodes)) for ind in ts.individuals()]
  File "/home/grg/.local/lib/python3.8/site-packages/pyslim/slim_tree_sequence.py", line 150, in <listcomp>
    npops = [len(set(self.node(n).population for n in ind.nodes)) for ind in ts.individuals()]
  File "/home/grg/.local/lib/python3.8/site-packages/pyslim/slim_tree_sequence.py", line 150, in <genexpr>
    npops = [len(set(self.node(n).population for n in ind.nodes)) for ind in ts.individuals()]
  File "/home/grg/.local/lib/python3.8/site-packages/pyslim/slim_tree_sequence.py", line 272, in node
    node = super(SlimTreeSequence, self).node(id_)
  File "/home/grg/.local/lib/python3.8/site-packages/tskit/trees.py", line 3989, in node
    metadata_decoder=self.table_metadata_schemas.node.decode_row,
  File "/home/grg/.local/lib/python3.8/site-packages/tskit/trees.py", line 3196, in table_metadata_schemas
    return self._table_metadata_schemas
AttributeError: 'SlimTreeSequence' object has no attribute '_table_metadata_schemas'
```

**Comment by petrelharp** [comment]
whoops, yes! This is fixed in master. I'll push out a release.

**Comment by petrelharp** [comment]
Ok, I've released v0.402, which should fix this.

(btw, I totally messed up having sane versioning numbers, I guess I'll have to fix that on the next go-round...)

**Comment by grahamgower** [comment]
Thanks for the quick fix @petrelharp!

**Comment by petrelharp** [comment]
Thanks for the quick report!
